# 1 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 2 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_MapScripts::
# 3 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 5 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Andrea::
# 6 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
# 7 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 9 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 10 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Connie::
# 11 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
# 12 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 14 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 15 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bridget::
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
# 17 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 19 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Olivia::
# 21 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
# 22 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 24 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 25 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Tiffany::
# 26 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
# 27 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 29 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 30 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Annika::
# 31 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
# 32 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
# 33 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 34 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 35 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Daphne::
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
# 37 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 39 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaIntro:
# 41 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll show you the sublime techniques\n"
# 42 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I learned from our LEADER JUAN!$"
# 43 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 44 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaDefeat:
# 45 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Please forgive me, JUAN…$"
# 46 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 47 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
# 48 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Watch what happens if you crack all\n"
# 49 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "the floor tiles.$"
# 50 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 51 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneIntro:
# 52 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The sight of JUAN conducting\n"
# 53 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "a battle…\p"
# 54 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The very beauty of it compelled me to\n"
# 55 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "become a TRAINER.$"
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 57 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneDefeat:
# 58 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You battled with more beauty than\n"
# 59 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I could muster…$"
# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 61 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
# 62 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The grace you bring to battle is\n"
# 63 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "fabulous.\p"
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh… I'm so fortunate to have found\n"
# 65 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "POKéMON.$"
# 66 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 67 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieIntro:
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I should teach you how harsh battles\n"
# 69 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "can be.$"
# 70 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 71 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieDefeat:
# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh.\n"
# 73 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You're strong.$"
# 74 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 75 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConniePostBattle:
# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll tell you something good.\p"
# 77 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "If you want to reach JUAN, you\n"
# 78 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "need to walk on each floor tile once.$"
# 79 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetIntro:
# 81 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The POKéMON GYM of the highest level\n"
# 82 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "in the HOENN region…\p"
# 83 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "That's the SOOTOPOLIS GYM.$"
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 85 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetDefeat:
# 86 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "What a high level you are!$"
# 87 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
# 89 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Rather than being satisfied by being\n"
# 90 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "in a strong GYM, I imagine training in\l"
# 91 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "other places will make you stronger.\l"
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "But above all, it looks more fun.$"
# 93 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 94 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaIntro:
# 95 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I train my POKéMON together with\n"
# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "JUAN.\p"
# 97 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Don't think I'm a pushover.$"
# 98 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 99 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaDefeat:
# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I was beaten…$"
# 101 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 102 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
# 103 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I think you have potential.\n"
# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Why don't you stay and train with us?$"
# 105 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 106 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyIntro:
# 107 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "A graceful glide across the ice while\n"
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "crossing no lines…\p"
# 109 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "A TRAINER putting on that performance\n"
# 110 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "would be elegantly beautiful!$"
# 111 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
# 113 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Well, excuse me?!$"
# 114 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 115 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "This is really obvious, but how strong\n"
# 117 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "you are as a TRAINER has nothing to do\l"
# 118 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "with how young or old you are.$"
# 119 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaIntro:
# 121 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I can battle with really rare POKéMON\n"
# 122 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "if you'd like.$"
# 123 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
# 125 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, there now! Did you have a good look\n"
# 126 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "at my POKéMON?$"
# 127 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 128 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
# 129 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I came to this GYM because JUAN\n"
# 130 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "praised me for my darling POKéMON.\p"
# 131 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, if only I'd met JUAN years ago\n"
# 132 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "when I was younger…$"
